# -*- coding: utf-8 -*-
"""Advance Mathematics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iBKTAId3IX3GaeCaq9motu-3fEA5lGge
"""

!pip install pandas numpy matplotlib scikit-learn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit

df = pd.read_csv("/content/data.csv", encoding='latin1')
df.head()

print(df.columns)

x = df["no2"].dropna().values

r = 102303596

ar = 0.05 * (r % 7)
br = 0.3 * ((r % 5) + 1)

z = x + ar * np.sin(br * x)

z_mean = np.mean(z)
z_std = np.std(z)
z_norm = (z - z_mean) / z_std

hist, edges = np.histogram(z_norm, bins=30, density=True)
centers = (edges[:-1] + edges[1:]) / 2

def pdf_model(val, c, lam, mu):
    return c * np.exp(-lam * (val - mu)**2)

c0 = hist.max()
lam0 = 1.0
mu0 = 0.0

params, _ = curve_fit(
    pdf_model,
    centers,
    hist,
    p0=[c0, lam0, mu0],
    bounds=(0, [10, 10, 5]),
    maxfev=50000
)

c_est, lambda_est, mu_est = params

print("FINAL PARAMETERS")
print("c =", c_est)
print("lambda =", lambda_est)
print("mu =", mu_est)

z_range = np.linspace(min(z_norm), max(z_norm), 300)

plt.hist(z_norm, bins=30, density=True, alpha=0.5, label="Empirical PDF")
plt.plot(z_range,
         pdf_model(z_range, c_est, lambda_est, mu_est),
         label="Fitted PDF")

plt.legend()
plt.title("PDF Fit")
plt.show()

low = np.percentile(z_norm, 1)
high = np.percentile(z_norm, 99)

z_range = np.linspace(low, high, 300)

plt.hist(z_norm, bins=30, density=True, alpha=0.5, label="Empirical PDF")

plt.plot(
    z_range,
    pdf_model(z_range, c_est, lambda_est, mu_est),
    label="Fitted PDF"
)

plt.xlim(low, high)
plt.legend()
plt.title("PDF Fit")
plt.show()